# Variables
@baseUrl = http://127.0.0.1:5000

# GET hello world
GET {{baseUrl}}/hello-world

###

# POST login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

# GET logout
GET {{baseUrl}}/logout


###

# GET all users
GET {{baseUrl}}/user

###

# GET specific logged user
GET {{baseUrl}}/user/2

###

# PUT update user password
PUT {{baseUrl}}/user/1
Content-Type: application/json

{
  "password": "admin123"
}


###

# POST user
POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "Pedro",
  "password": "admin"
}