services:
  db:
    image: mysql:latest
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    volumes:
      - C:/Docker-volumes/mysql:/var/lib/mysql